name = "intltool"
version = "0.51.0"
summary = "Imported LFS stage8 script: 8.45-intltool.sh"
license = "LFS"

deps = ["xml-parser"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"
sha256 = "67c74d94196b153b774ab9f89b2fa6c6ba79352407037c8c14d5aeb334e959cd"
