name = "perl"
version = "5.42.0"
summary = "Imported LFS stage8 script: 8.43-perl.sh"
license = "LFS"

deps = ["less", "libxcrypt"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://www.cpan.org/src/5.0/perl-5.42.0.tar.xz"
sha256 = "73cf6cc1ea2b2b1c110a18c14bbbc73a362073003893ffcedc26d22ebdbdd0c3"
