name = "dbus"
version = "1.16.2"
summary = "Imported LFS stage8 script: 8.77-dbus.sh"
license = "LFS"

deps = ["expat"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz"
sha256 = "0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"
