name = "jinja2"
version = "3.1.6"
summary = "Imported LFS stage8 script: 8.75-jinja2.sh"
license = "LFS"

deps = ["markupsafe"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://pypi.org/packages/source/J/Jinja2/jinja2-3.1.6.tar.gz"
sha256 = "0137fb05990d35f1275a587e9aee6d56da821fc83491a0fb838183be43f66d6d"
