name = "glib"
version = "2.84.4"
summary = "Core application building blocks library"
license = "LGPL-2.1-or-later"

deps = ["libffi", "pcre2", "python"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "url"
url = "https://download.gnome.org/sources/glib/2.84/glib-2.84.4.tar.xz"
sha256 = "8a9ea10943c36fc117e253f80c91e477b673525ae45762942858aef57631bb90"
