name = "packaging"
version = "25.0"
summary = "Imported LFS stage8 script: 8.53-packaging.sh"
license = "LFS"

deps = ["flit-core"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://files.pythonhosted.org/packages/source/p/packaging/packaging-25.0.tar.gz"
sha256 = "d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f"
