name = "tar"
version = "1.35"
summary = "Imported LFS stage8 script: 8.71-tar.sh"
license = "LFS"

deps = ["gzip", "xz", "bzip2", "zstd", "lz4"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
sha256 = "4d62ff37342ec7aed748535323930c7cf94acf71c3591882b26a7ea50f3edc16"
