name = "base"
summary = "Minimal runtime OS only: boot, login, networking, TLS, core userland, and package consumption"
ports = [
  "man-pages",
  "iana-etc",
  "linux-api-headers",
  "glibc",
  "zlib",
  "bzip2",
  "xz",
  "lz4",
  "zstd",
  "file",
  "readline",
  "attr",
  "acl",
  "libcap",
  "libxcrypt",
  "shadow",
  "ncurses",
  "sed",
  "psmisc",
  "gettext",
  "grep",
  "bash",
  "gdbm",
  "gcc-runtime",
  "expat",
  "inetutils",
  "curl",
  "less",
  "openssl",
  "libffi",
  "kmod",
  "coreutils",
  "diffutils",
  "gawk",
  "findutils",
  "grub",
  "gzip",
  "iproute2",
  "kbd",
  "libpipeline",
  "tar",
  "systemd",
  "dbus",
  "man-db",
  "procps",
  "util-linux",
  "e2fsprogs"
]
