name = "development"
summary = "Development stack layered on top of base: compilers, build systems, languages, docs, and developer tools"
ports = [
  "m4",
  "bc",
  "flex",
  "tcl",
  "expect",
  "dejagnu",
  "pkgconf",
  "binutils",
  "gn",
  "gmp",
  "mpfr",
  "mpc",
  "cmake",
  "git".
  "gcc",
  "bison",
  "libtool",
  "gperf",
  "perl",
  "xml-parser",
  "intltool",
  "autoconf",
  "automake",
  "libelf",
  "python",
  "flit-core",
  "packaging",
  "wheel",
  "setuptools",
  "ninja",
  "meson",
  "groff",
  "texinfo",
  "vim",
  "markupsafe",
  "jinja2",
  "patch"
]
