name = "pciaccess"
version = "0.18.1"
summary = "Generic PCI access library"
license = "MIT"

deps = ["zlib"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "url"
url = "https://xorg.freedesktop.org/archive/individual/lib/libpciaccess-0.18.1.tar.xz"
sha256 = "4af43444b38adb5545d0ed1c2ce46d9608cc47b31c2387fc5181656765a6fa76"
