name = "giflib"
version = "latest"
summary = "GIF image library"
license = "MIT"

deps = []

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "git"
url = "https://github.com/mirrorer/giflib.git"
