name = "jpeg-turbo"
version = "latest"
summary = "JPEG image codec"
license = "BSD-3-Clause"

deps = []

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "git"
url = "https://github.com/libjpeg-turbo/libjpeg-turbo.git"

