name = "pcre2"
version = "10.45"
summary = "Perl-compatible regular expression library"
license = "BSD-3-Clause"

deps = []

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "url"
url = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.45/pcre2-10.45.tar.gz"
sha256 = "0e138387df7835d7403b8351e2226c1377da804e0737db0e071b48f07c9d12ee"
