name = "man-db"
version = "2.13.1"
summary = "Imported LFS stage8 script: 8.78-man-db.sh"
license = "LFS"

deps = ["gdbm", "libpipeline", "less"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://download.savannah.gnu.org/releases/man-db/man-db-2.13.1.tar.xz"
sha256 = "8afebb6f7eb6bb8542929458841f5c7e6f240e30c86358c1fbcefbea076c87d9"
