name = "findutils"
version = "4.10.0"
summary = "Imported LFS stage8 script: 8.62-findutils.sh"
license = "LFS"

deps = []

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz"
sha256 = "1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5"
