name = "markupsafe"
version = "3.0.2"
summary = "Imported LFS stage8 script: 8.74-markupsafe.sh"
license = "LFS"

deps = ["vim"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://pypi.org/packages/source/M/MarkupSafe/markupsafe-3.0.2.tar.gz"
sha256 = "ee55d3edf80167e48ea11a923c7386f4669df67d7994554387f84e7d8b0a2bf0"
