name = "libevdev"
version = "latest"
summary = "Wrapper library for evdev devices"
license = "MIT"

deps = []

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "git"
url = "https://gitlab.freedesktop.org/libevdev/libevdev.git"

