name = "texinfo"
version = "7.2"
summary = "Imported LFS stage8 script: 8.72-texinfo.sh"
license = "LFS"

deps = ["tar"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/texinfo/texinfo-7.2.tar.xz"
sha256 = "0329d7788fbef113fa82cb80889ca197a344ce0df7646fe000974c5d714363a6"
