name = "gcc"
version = "15.2.0"
summary = "Imported LFS stage8 script: 8.29-gcc.sh"
license = "LFS"

deps = ["shadow"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.xz"
sha256 = "438fd996826b0c82485a29da03a72d71d6e3541a83ec702df4271f6fe025d24e"
