name = "binutils"
version = "2.45"
summary = "Imported LFS stage8 script: 8.20-binutils.sh"
license = "LFS"

deps = ["pkgconf"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://sourceware.org/pub/binutils/releases/binutils-2.45.tar.xz"
sha256 = "c50c0e7f9cb188980e2cc97e4537626b1672441815587f1eab69d2a1bfbef5d2"
