name = "make"
version = "4.4.1"
summary = "Imported LFS stage8 script: 8.69-make.sh"
license = "LFS"

deps = ["libpipeline"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
