name = "bash"
version = "5.3"
summary = "Imported LFS stage8 script: 8.36-bash.sh"
license = "LFS"

deps = ["readline", "ncurses"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"


[src]
type = "url"
url = "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"
sha256 = "0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"
