name = "cmake"
version = "4.0.3"
summary = "CMake build system"
license = "BSD-3-Clause"

deps = ["curl", "gcc", "gcc-runtime", "make", "openssl", "zlib"]

install_mode = "store"

[build]
system = "make"

[scripts]
build = "build.sh"
install = "install.sh"

[src]
type = "url"
url = "https://github.com/Kitware/CMake/releases/download/v4.0.3/cmake-4.0.3.tar.gz"
sha256 = "8d3537b7b7732660ea247398f166be892fe6131d63cc291944b45b91279f3ffb"
